// <auto-generated />
namespace EurofinsDigitalWallet.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedInvestmentsTableAndAddedRelationWithApplicaionUserAndInvestementType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedInvestmentsTableAndAddedRelationWithApplicaionUserAndInvestementType));
        
        string IMigrationMetadata.Id
        {
            get { return "202006021433315_AddedInvestmentsTableAndAddedRelationWithApplicaionUserAndInvestementType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
